---
# Output any variables that start with couchbase_*
- name: Show all Couchbase variables
  debug:
    var: vars[item]
  with_items: "{{ lookup('varnames', 'couchbase_.+').split(',') }}"
  tags:
    - couchbase_debug

- name: Preflight
  ansible.builtin.include_tasks: "{{ item }}"
  with_fileglob:
    - preflight/*.yml
  tags:
    - couchbase_install
    - couchbase_debug
    - couchbase_configure
    - couchbase_os
    - couchbase_firewalld
    - couchbase_rebalance
    - couchbase_server_groups
    - couchbase_buckets
    - couchbase_sample_buckets
    - couchbase_audit
    - couchbase_autofailover
    - couchbase_password_policy
    - couchbase_query_settings
    - couchbase_index_settings
    - couchbase_security_settings
    - couchbase_rebalance_settings
    - couchbase_notifications
    - couchbase_alerts
    - couchbase_compaction
    - couchbase_xdcr
    - couchbase_ldap
    - couchbase_users
    - couchbase_user_groups
    - couchbase_indexes

# Install the OS specific installer in the install/ directory
- include_tasks: "{{ item }}"
  with_first_found:
    - "install/{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "install/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "install/{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "install/{{ ansible_distribution | lower }}.yml"
    - "install/{{ ansible_os_family | lower }}.yml"
  tags:
    - couchbase_install

- name: Make sure Couchbase Server is started and enabled
  service:
    name: couchbase-server
    state: started
    enabled: true
  tags:
    - couchbase_install
    - couchbase_configure

- include_tasks: os/disable_thp.yml
  when: couchbase_os.disable_thp | default(false)
  tags:
    - couchbase_os
    - couchbase_disable_thp

- name: Tuning variables
  when: couchbase_os.kernel_tunings | default(false)
  include_vars: ../defaults/tunings.yml
  tags:
    - couchbase_os
    - couchbase_disable_thp
    - couchbase_tunings
    - couchbase_user_limits

- include_tasks: os/tunings.yml
  when: couchbase_os.kernel_tunings | default(false)
  tags:
    - couchbase_os
    - couchbase_kernel_tunings

- include_tasks: os/user_limits.yml
  when: couchbase_os.user_limits | default(false)
  tags:
    - couchbase_os
    - couchbase_user_limits

- include_tasks: os/firewalld.yml
  when: couchbase_os.firewalld | default(false)
  tags:
    - couchbase_firewalld

- name: Register a variable to set the master/configuration node
  set_fact:
    couchbase_master: "{{ lookup('vars', couchbase_hostname_var) }}"
  when: couchbase_master is not defined and couchbase_nodes[0].hostname == lookup('vars', couchbase_hostname_var)
  tags:
    - couchbase_configure
    - couchbase_rebalance
    - couchbase_server_groups
    - couchbase_buckets
    - couchbase_sample_buckets
    - couchbase_audit
    - couchbase_autofailover
    - couchbase_password_policy
    - couchbase_query_settings
    - couchbase_index_settings
    - couchbase_security_settings
    - couchbase_rebalance_settings
    - couchbase_notifications
    - couchbase_alerts
    - couchbase_compaction
    - couchbase_xdcr
    - couchbase_ldap
    - couchbase_users
    - couchbase_user_groups
    - couchbase_indexes

- include_tasks: configure/wait_for_nodes.yml
  tags:
    - couchbase_configure
    - couchbase_rebalance

- include_tasks: configure/initialize_nodes.yml
  tags:
    - couchbase_configure
    - couchbase_initialize_nodes

- include_tasks: configure/initialize_cluster.yml
  tags:
    - couchbase_configure
    - couchbase_initialize_cluster

- include_tasks: configure/enforce_cluster_name.yml
  tags:
    - couchbase_configure
    - couchbase_enforce_cluster_name

- include_tasks: configure/audit.yml
  tags:
    - couchbase_configure
    - couchbase_audit

- include_tasks: configure/notifications.yml
  tags:
    - couchbase_configure
    - couchbase_notifications

- include_tasks: configure/alerts.yml
  tags:
    - couchbase_configure
    - couchbase_alerts

- include_tasks: configure/compaction.yml
  tags:
    - couchbase_configure
    - couchbase_compaction

- include_tasks: configure/rebalance_settings.yml
  tags:
    - couchbase_configure
    - couchbase_rebalance_settings

- include_tasks: configure/security_settings.yml
  tags:
    - couchbase_configure
    - couchbase_security_settings

- include_tasks: configure/password_policy.yml
  tags:
    - couchbase_configure
    - couchbase_password_policy

- include_tasks: configure/query_settings.yml
  tags:
    - couchbase_configure
    - couchbase_query_settings

- include_tasks: configure/index_settings.yml
  tags:
    - couchbase_configure
    - couchbase_index_settings

- include_tasks: configure/ldap.yml
  tags:
    - couchbase_configure
    - couchbase_ldap

- include_tasks: configure/add_nodes.yml
  tags:
    - couchbase_configure
    - couchbase_add_nodes

- include_tasks: configure/wait_for_cluster.yml
  tags:
    - couchbase_configure
    - couchbase_rebalance

- include_tasks: configure/rebalance.yml
  tags:
    - couchbase_configure
    - couchbase_rebalance

- include_tasks: configure/server_groups.yml
  tags:
    - couchbase_configure
    - couchbase_server_groups

- include_tasks: configure/buckets.yml
  tags:
    - couchbase_configure
    - couchbase_buckets

- include_tasks: configure/sample_buckets.yml
  tags:
    - couchbase_configure
    - couchbase_sample_buckets

- include_tasks: configure/autofailover.yml
  tags:
    - couchbase_configure
    - couchbase_audit

- include_tasks: configure/users.yml
  tags:
    - couchbase_configure
    - couchbase_users
    - couchbase_user_groups

- include_tasks: configure/indexes.yml
  tags:
    - couchbase_configure
    - couchbase_indexes

- include_tasks: configure/xdcr.yml
  tags:
    - couchbase_configure
    - couchbase_xdcr
